### PR TITLE
[TASK] Add also region to be relational to static_info_tables

### PR DESCRIPTION
**Pull request by BastianBalthasarBux**
Adds a selector for the region/country_zone too, but no migration service for it.

### CODE REVIEW

**Comment by swisschocolate-zz** [comment]
Exactly what I needed, thanks BBB. Looking forward for the merge ;-)

**Comment by georgringer** [comment]
@BastianBalthasarBux please add a check if static_info_tables is installed or not

**Comment by BastianBalthasarBux** [comment]
> @BastianBalthasarBux please add a check if static_info_tables is installed or not

Shouldn't this be done in the whole extension itself? IMHO this is not a task related to my PR.

**Comment by georgringer** [comment]
You are extending it with relation to this extension...

**Comment by BastianBalthasarBux** [comment]
Whut?

The scope first (your version) was only to add **relations to countries**.
I just added **relation to country_zones** too.

**BOTH tables are part of static_info_tables.** I really cannot see, what my PR changes concerning dependencies. The extension depends on static_info_tables, if you merge my PR or not.

**Comment by georgringer** [comment]
sry @BastianBalthasarBux you are of course correct

**Pull request merged**
